export const ARTICLE_CONSTANTS = {
  DEFAULT_LIMIT: 20,
  DEFAULT_OFFSET: 0,
  LIMIT_MIN: 1,
  OFFSET_MIN: 0,
  SLUG_LOWERCASE: true,
  SLUG_RANDOM_START: 2,
  SLUG_RANDOM_END: 6,
  TITLE_MIN_LENGTH: 5,
  TITLE_MAX_LENGTH: 100,
  DESCRIPTION_MIN_LENGTH: 5,
  DESCRIPTION_MAX_LENGTH: 100,
};